version: 2.1
orbs:
  cypress: cypress-io/cypress@1
workflows:
  build:
    jobs:
      - cypress/run:
          name: Development tests
          filters:
            branches:
              ignore:
                - master
      - cypress/run:
          name: Production tests
          spec: cypress/integration/*
          filters:
            branches:
              only:
                - master
